name: Reusable Workflow to Deploy .NET App

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string

env:
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      package-name: ${{ inputs.package-name }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.package-name }}


      - name: Print name of App Service to deploy to
        run: echo "App will be deployed to ${{ env.package-name }}"

      - name: List files in root directory
        run: ls -la
