name: Reusable Workflow to Build & Deploy .NET App

on:
  workflow_dispatch:

env:
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true

jobs:
  build:
    uses: ./.github/workflows/reusable-WeatherForecast.build.yml

  deploy:
    needs: build
    uses: ./.github/workflows/reusable-WeatherForecast.deploy.yml
    with:
      package-name: WeatherForecast.service