name: upper-build

on:
  push:
    paths:
      - ".github/workflows/upper-build.yml"
      - "upper/**"
  workflow_dispatch: # manual

jobs:
  build:
    permissions:
      # # Permissions to create releases
      contents: write
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: upper
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache-dependency-path: ./upper/go.sum
      - run: ls
      - run: go build
      - run: ls
      - run: go test -v

      # # Create a release if this is a tag
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: ./upper/bin/upper*
          body: "Binaries for the upper (go) command line tool!!!"
          tag_name: ${{ github.ref_name }}
        if: startsWith(github.ref, 'refs/tags/')

      # # Publish artifacts for all builds
      - name: Upload upper artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./upper/upper*
          name: "build-${{ matrix.os }}"

  # # Package the upper binary
  image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: docker version
      - run: docker image build -t upper .
        working-directory: ./upper
      - name: test it
        run: docker container run upper hello wes
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker tag upper ghcr.io/${{ github.repository_owner }}/upper:latest
      - run: docker tag upper ghcr.io/${{ github.repository_owner }}/upper:${{ github.ref_name }}
      - run: docker push ghcr.io/${{ github.repository_owner }}/upper:latest
      - run: docker push ghcr.io/${{ github.repository_owner }}/upper:${{ github.ref_name }}
