name: upper-build

on:
  push:
    paths:
      - ".github/workflows/upper-build.yml"
      - "upper/**"
  workflow_dispatch: # manual

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      # # Permissions to create releases
      contents: write

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    defaults:
      run:
        working-directory: upper

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache-dependency-path: ./upper/go.sum

      - name: Build binary
        run: go build -o bin/upper

      - name: Run unit tests
        run: go test ./... -v

      - name: Run static analysis
        run: go vet ./...

      # # Publish artifacts for all builds
      - name: Upload upper artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "build-${{ matrix.os }}"
          path: ./upper/bin/upper*

      # # Create a release if this is a tag
      - name: Create GitHub Release
        # if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: ./upper/bin/upper*
          body: "Binaries for the upper (go) command line tool!!!"
          tag_name: ${{ github.ref_name }}


  # # Package the upper binary
  image:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      # # Permissions to write to the GitHub Container Registry
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Docker version
        run: docker version

      - name: Build Docker image
        working-directory: ./upper
        run: docker image build -t upper .

      - name: Smoke test Docker image
        run: docker container run upper hello wes

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and push Docker images
        run: |
          docker tag upper ghcr.io/${{ github.repository_owner }}/upper:latest
          docker push ghcr.io/${{ github.repository_owner }}/upper:latest

          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            docker tag upper ghcr.io/${{ github.repository_owner }}/upper:${{ github.ref_name }}
            docker push ghcr.io/${{ github.repository_owner }}/upper:${{ github.ref_name }}
          fi
